### ISSUE TITLE
Support Hex, Octol and binary literal numbers

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#125]
https://doc.rust-lang.org/rust-by-example/primitives/literals.html

**Comment by SimplyTheOther** [comment]
There should already be support for hex, octal and binary integer literals - they are lexed as "integer literal" tokens in the lexer, and then treated as any other integer afterward (e.g. for the parser or for literals stored in literal expressions or whatever). While writing the lexer, I was under the impression that they were just a different way of representing integer literals rather than something that should truly be considered distinct. I got that impression from the spec [here](https://doc.rust-lang.org/reference/tokens.html#integer-literals), which describes them all as types of integer literal.

**Comment by philberty** [comment]
From following the code i think your right i will write a test case so we can close the issue. I have been creating issues to help with progress tracking for the compiler in my reports.
