### ISSUE TITLE
Create an AST node for inline assembly

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1567]

**Comment by CohenArthur** [comment]
Aaaaah fantastic, so the `ast::InlineAsm` kind of node is only generated after expansion. We're gonna need to change our pipeline a little then or at least make sure that macro name resolution happens before expansion. This is something that ties into #1077

**Comment by liushuyu** [comment]
1:1 translation:

```cpp
// Inline-assembly specific options
enum InlineAsmOptions
{
  PURE = 1 << 0,
  NOMEM = 1 << 1,
  READONLY = 1 << 2,
  PRESERVES_FLAGS = 1 << 3,
  NORETURN = 1 << 4,
  NOSTACK = 1 << 5,
  ATT_SYNTAX = 1 << 6,
  RAW = 1 << 7,
  MAY_UNWIND = 1 << 8,
};

struct InlineAsmRegOrClass
{
public:
  /* constraint is a string because Rust inline assembly allows explicitly
     specifying a CPU-architectural-specific register */
  std::string constraint;
  /* is the constraint a class of registers (e.g. general registers)? or is it a
   * specific register (e.g. rax)? */
  bool is_constraint_class;
  Identifier name;
  Location locus;
};

struct InlineAsmOperand
{
public:
  enum RegisterType
  {
    IN,
    INOUT,
    OUT,
    LATEOUT,
    INLATEOUT,
    CONST,
    SYMBOL,
  };

  InlineAsmRegOrClass reg;
  bool is_anon_const;
  RegisterType type;
  // primary expression; in `inout` type, this is the in_expr
  std::unique_ptr<Expr> expr;
  // secondary expression, can be nullptr; this is the out_expr
  std::unique_ptr<Expr> other_expr;
  Location locus;
};

struct InlineAsmPlaceHolder
{
  size_t operand_idx;
  char modifier;
  Location locus;
};

struct InlineAsmTemplatePiece
{
  bool is_placeholder;
  union
  {
    std::string string;
    InlineAsmPlaceHolder placeholder;
  };
};
```

**Comment by mvvsmk** [comment]
Hey @CohenArthur I would like to take up this issue if it's still open. :)

**Comment by CohenArthur** [comment]
@mvvsmk great, thanks :) Note that this will be a bit difficult to test and not really usable until #1606 is merged. But your work will still be really useful when we get to that point!

**Comment by mvvsmk** [comment]
Undustood, I'll get it ready, and we can get rid of bugs if any when it's ready for testing. :)

**Comment by mvvsmk** [comment]
Hey, @CohenArthur , I have a few doubts regarding the implementation of the InlineAsm; as I went through the rustc guide to draw parallels but got a bit lost, I hope you can clear some stuff out.

- In rustc the asm! macro is implemented in rustc_builtin_macros and outputs an InlineAsm AST node. While we need a subdirectory for this, where should I implement it?

- Earlier, I did [this](https://github.com/mvvsmk/gccrs/commit/0e764ab9d3858c152871c029194a2d50a70267dd). But after seeing the rustc guide, I thought it needed all the member functions, too, and thought to continue in the same file.

- Also, just so that I don't have any doubts left,
AST visitor (in ast-visitor.h) -> sends expression -> The AST node constructor receives it(in this case rust-expr.h) -> assigns are respective values?
I found that was the flow of logic. Please correct me if I am wrong.

- Lastly, what is the use of rust-ast-dump and rust-ast-fragment files? I had heard about a ast-dump, but what about an ast-fragment.

**Comment by mvvsmk** [comment]
Thank you so much for clearing this out. @CohenArthur 

> As mentionned earlier, this should not be done yet :) to do this, the compiler needs to perform proper macro name resolution to "make sure" that what we're expanding is inline assembly. Inline assembly is done, as you mentioned, by calling this macro.

and 

> It depends of the visitors and in what pass of the pipeline you are. Most of the time, we create AST nodes directly (e.g in rust-parse-impl.h) and then simply visit them in one of the visitors, like the AST::Dump for example which only accesses members of each node.

I have already created the class, though, for the past few days, I have been trying to find more parallels between the rustc compiler and gccrs to see how we go about it. I'll generate a PR/WIP when I see that there is nothing more I could add, where you could suggest something I might have missed.

Thank you again for clearing all my doubts, though sometimes a few might seem very silly. :)

**Comment by CohenArthur** [comment]
No worries! And yes, feel free to submit a draft pull-request and ask for a review :) thanks again for working on this
