### ISSUE TITLE
Crash with zero-length array

### ISSUE THREAD

**Issue by YizhePKU** [Rust-GCC/gccrs#260]
Input program:
```
fn main() {
    let array: [i64; 0] = [];
}
```

Output:
```
Preparing to parse files.
SUCCESSFULLY PARSED CRATE
ran register_plugins (with no body)
SUCCESSFULLY REGISTERED PLUGINS
started injection
finished injection
SUCCESSFULLY FINISHED INJECTION
started expansion
finished expansion
SUCCESSFULLY FINISHED EXPANSION
rust1: internal compiler error: in get_array_elems, at rust/ast/rust-expr.h:1196
0x85cc83 Rust::AST::ArrayExpr::get_array_elems()
	../../gccrs/gcc/rust/ast/rust-expr.h:1196
0x85cc83 Rust::Resolver::ResolveExpr::visit(Rust::AST::ArrayExpr&)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve-expr.h:200
0x747759 Rust::AST::ArrayExpr::accept_vis(Rust::AST::ASTVisitor&)
	../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5093
0x862650 Rust::Resolver::ResolveExpr::go(Rust::AST::Expr*, unsigned int)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve-expr.h:36
0x862650 Rust::Resolver::ResolveStmt::visit(Rust::AST::LetStmt&)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve-stmt.h:56
0x7484e9 Rust::AST::LetStmt::accept_vis(Rust::AST::ASTVisitor&)
	../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5741
0x85ac7c Rust::Resolver::ResolveStmt::go(Rust::AST::Stmt*, unsigned int)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve-stmt.h:37
0x85ac7c operator()
	../../gccrs/gcc/rust/resolve/rust-ast-resolve.cc:336
0x85ac7c _M_invoke
	/usr/include/c++/9/bits/std_function.h:285
0x84275d std::function<bool (Rust::AST::Stmt*)>::operator()(Rust::AST::Stmt*) const
	/usr/include/c++/9/bits/std_function.h:688
0x85b862 Rust::AST::BlockExpr::iterate_stmts(std::function<bool (Rust::AST::Stmt*)>)
	../../gccrs/gcc/rust/ast/rust-expr.h:2956
0x85b862 Rust::Resolver::ResolveExpr::visit(Rust::AST::BlockExpr&)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve.cc:335
0x7479d9 Rust::AST::BlockExpr::accept_vis(Rust::AST::ASTVisitor&)
	../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5225
0x863027 Rust::Resolver::ResolveExpr::go(Rust::AST::Expr*, unsigned int)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve-expr.h:36
0x863027 Rust::Resolver::ResolveItem::visit(Rust::AST::Function&)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve-item.h:111
0x747ea3 Rust::AST::Function::accept_vis(Rust::AST::ASTVisitor&)
	../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5453
0x85b5d6 Rust::Resolver::ResolveItem::go(Rust::AST::Item*)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve-item.h:37
0x85b5d6 Rust::Resolver::NameResolution::go(Rust::AST::Crate&)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve.cc:319
0x85c45b Rust::Resolver::NameResolution::Resolve(Rust::AST::Crate&)
	../../gccrs/gcc/rust/resolve/rust-ast-resolve.cc:297
0x786d61 Rust::Session::parse_file(char const*)
	../../gccrs/gcc/rust/rust-session-manager.cc:524
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
Attempting to parse file: test.rs
```

**Comment by philberty** [comment]
looks as though its hitting the assertion over in:

```
  std::unique_ptr<ArrayElems> &get_array_elems ()
  {
    rust_assert (internal_elements != nullptr);
    return internal_elements;
  }
  ```
  
  ```
  rust1: internal compiler error: in get_array_elems, at rust/ast/rust-expr.h:1157
0xa2abd0 Rust::AST::ArrayExpr::get_array_elems()
        ../../gccrs/gcc/rust/ast/rust-expr.h:1157
0xa2abd0 Rust::Resolver::ResolveExpr::visit(Rust::AST::ArrayExpr&)
        ../../gccrs/gcc/rust/resolve/rust-ast-resolve-expr.h:191

  ```

We could have a helper like bool has_elems that returns wether that is null or not.

**Comment by YizhePKU** [comment]
Alternatively, we can use a zero-length vector instead of nullptr to represent a zero-length array. That'll disallow nullptr altogether and eliminate many egde cases.

**Comment by YizhePKU** [comment]
Related: this seems to crash as well.

```Rust
fn main() {
    let array = ["hello", 123];
}
```

**Comment by philberty** [comment]
I got this when i tried it:

```
SUCCESSFULLY FINISHED EXPANSION 
BEGIN POST-EXPANSION AST DUMP
beginning crate recursive as-string
END POST-EXPANSION AST DUMP
test.rs:2:27: error: expected [&str] got [<integer>]
    2 |     let array = ["hello", 123];
      |                           ^
test.rs:2:9: warning: unused name
    2 |     let array = ["hello", 123];
      |         ^

Analyzing compilation unit

```

The location is off for the error though.

**Comment by philberty** [comment]
that should be added as a fail test case though I don't think we have one for that.

**Comment by YizhePKU** [comment]
Just realized that crash was on a modified binary. Nevermind then.

> that should be added as a fail test case though I don't think we have one for that.

Yep.

**Comment by SimplyTheOther** [comment]
> 
> We could have a helper like bool has_elems that returns wether that is null or not.

I believe there already is one (or at least I intended to make one) - I would imagine I would call it has_array_elems() or something like that.



> Alternatively, we can use a zero-length vector instead of nullptr to represent a zero-length array. That'll disallow nullptr altogether and eliminate many egde cases.

Currently, the ArrayExpr structure stores a pointer to an ArrayElems instance. ArrayElems is an abstract class that currently has two concrete child classes: ArrayElemsValues (or something like that), which includes a vector of values, and ArrayElemsCopied (or something), which stores one value and an expression describing the amount of copies it should make of that value. This corresponds to the two ways you can initialise an array in Rust. 

As such, representation via nullptr was chosen because having no values technically doesn’t conceptually fit either, and also it saves (an admittedly small amount of) memory. 

I think there are three different options we could take here:

* Keep the current representation and just ensure we use has_array_elems before trying to access get_array_elems. Advantages: minimal code changes. Disadvantages: slightly increased verbosity, perhaps violation of encapsulation, may lead to more bugs in future.
* Change the parse result of an empty array to give an ArrayElemsValues with an empty vector (and prevent array elements from ever being null). Advantages: relatively few code changes, additional safety. Disadvantages: wasted memory (3 pointers for vector plus vtable), somewhat more expensive to tell if empty (pointer dereference plus virtual function call), possible non-intuitive nature that could lead to future logic errors.
* Make a third ArrayElems child called “ArrayElemsEmpty” or something that stores no data. Advantages: more intuitive while preserving safety, less additional memory usage (only vtable). Disadvantages: more significant code changes required (e.g. adding support to all visitors used), still uses additional memory.

**Comment by YizhePKU** [comment]
> As such, representation via nullptr was chosen because having no values technically doesn’t conceptually fit either

Not exactly. There're two ways to write an empty array, `[]` and `[value; 0]`. They correspond to ArrayElemsValues and ArrayElemsCopied respectively. Although they both represent an empty array, `[value; 0]` comes with additional type information(it can only hold elements of the same type as `value`).

**Comment by YizhePKU** [comment]
Here's what I've tried. I disallowed `nullptr` and modified the parsing code so that they generate an empty `ArrayElemsValues`.

The type-checking logic assumes that there's at least one element in `ArrayElemsValues` so that its type can be immediately fixed. I fixed it by returning an `InferType` when no elements are in the array. I made a new hir_id for the `InferType`.

It still doesn't work. The compiler crashed at the assertion in `TyTy::ArrayType::get_type()`, presumably because the `InferType` that I created isn't in the lookup table.

This is getting very hard. I'm not sure how to proceed.

I noticed that philberty just opened a related PR(#268). Maybe I'll come back to this when that PR is merged.

**Comment by philberty** [comment]
@YizhePKU I think you are on the right track there is an open bug about inference variables on array types #258 which that PR #268 fixes so it might be worth rebasing your work against that. 

I wanted to add you as a reviewer to that PR but I am unable to select you for some reason.

**Comment by philberty** [comment]
Also when creating an implict inference variable it would be worth while creating a static helper on the TyCtx object in that PR that i created which creates a General inference variable and auto adds it to the lookup table but also makes sure that HirId is unused. This object will slowly turn more and more into the tyctx.at style thing in rustc.
