### ISSUE TITLE
Fails to fold capacity constant

### ISSUE THREAD

**Issue by YizhePKU** [Rust-GCC/gccrs#296]
It seems like constants folding doesn't work for array capacity yet.

```Rust
fn main() {
    let arr = ["Hello"; 1 + 2];
}

// test.rs:2:25: fatal error: failed to fold capacity constant
```

```Rust
fn main() {
    let arr: [i64; 1 + 2];
}

// array_fold_type.rs:2:20: error: non-constant value
```

Maybe constant folding is simply not implemented yet? If so I'll mark the test in PR #288 as skip.

**Comment by philberty** [comment]
Yeah this is a good bug to fix. The reason it is like this was the abstraction of generic were using specified a size_t for array capacity and instead of fixing that i went with this hack over in:

https://github.com/Rust-GCC/gccrs/blob/fbe9e08d952187cb70e71d284ce1e4cd50a302fe/gcc/rust/typecheck/rust-hir-type-check-type.h#L28

This class should be removed.

Then ArrayType should reference the HIR::Expr for the constant and we can remove the unify checks for size for now until we get a better solution for folding constants in the Front-end specifically. Though GCC might give us this in the middle-end for free.


https://github.com/Rust-GCC/gccrs/blob/fbe9e08d952187cb70e71d284ce1e4cd50a302fe/gcc/rust/backend/rust-compile-context.h#L402

This call should take the referenced expression which could be compiled into a GCC::Bexpresion* with CompileExpr::Compile(array_capacity_tree).

It also means your going to handle the case were we infer the size from a simple initilizer like:

let a = [1,2,3]; The code in place should count this for you but it will need turned into an implicit HIR::LiteralExpr for the ArrayType

**Comment by philberty** [comment]
I started to rethink this one a bit and realised we can reuse fold-const.c from the backend code. It will be a little wierd but we might as well reuse it. Not sure how well error handling will be but I will knock up a PoC to see how it might work this week hopefully.

**Comment by dkm** [comment]
>  fold-const.c

wouldn't this make gccrs dependent on gcc ? Or are you thinking on wrapping this as you did with the other part of GCC ?

**Comment by philberty** [comment]
Yes it would but in PR #383 I added another wrapper over them I would really appreciate @tschwinge and @dkm or @davidmalcolm to review this it feels very janky in 2 places.

1. where we want to be able to print the array capacity for nice error messages
2. how we handle copied arrays
