### ISSUE TITLE
OpenMP, OpenACC

### ISSUE THREAD

**Issue by benman1** [Rust-GCC/gccrs#32]
Hi
This looks cool. 

I only have a stupid question, really (apologies): can you mix up rust with openmp/openacc directives? Could you give an example?

Thanks!

**Comment by philberty** [comment]
No question is stupid. I have some thoughts on this a few years ago let me see if i can find them on my google drive.

**Comment by philberty** [comment]
Unfortunately my notes are pretty old on this and i was targeting rust 0.8 then, i think it would muddy the water if i shared them at this stage.

Do you have an idea of what you would like to see for openmp?

I reckon something like pragma omp parallel could be handled with a directive quite easily (might require some wrapper code depending on calling conventions) but i am unsure about how to handle everything else at this stage.

**Comment by bjorn3** [comment]
Is OpenMP actually a good fit for rust? There is already for example rayon, which both supports turning usage of regular iterators into parallel iterators by replacing `.iter()` with `.par_iter()` and has a thread pool. The standard library has the `Mutex` type for synchronization which makes it impossible to forget to lock before accessing data. All these things combined pretty much cover all features of OpenMP, right?

**Comment by philberty** [comment]
I am looking at it from the perspective if we were to support openmp how could we do it rather than is it a fit for rust. But your not wrong i personally am not a fan of these libraries but they are popular in academia from what i know.

From talking to some friends in university in physics they liked openmp only because you could write single threaded code in C then throw in some pragma's and know it did the threading stuff. 

There are simd pragama's as well which is interesting to think about but would need some thought, i mean if you can some C code and change how you write it a bit and use more loops GCC knows to use simd where available. So to create a full openmp implementation is hard to handle all the directives possible and combinations.

https://bisqwit.iki.fi/story/howto/openmp/

**Comment by bjorn3** [comment]
> From talking to some friends in university in physics they liked openmp only because you could write single threaded code in C then throw in some pragma's and know it did the threading stuff.

Same thing with rayon: replace `iter()` with `par_iter()`.

**Comment by benman1** [comment]
What I find amazing in OpenMP (and OpenACC) is not only how easy it is to
parallelise code (and do reductions), but also that you can change if you
want to run on CPU, GPU, or even FPGA (with some restrictions).

That said, I'm still a bit new to rust, and I still have to compare rayon
properly.

----

**Comment by dkm** [comment]
I think this can be closed. If we want to continue the discussion, this can be moved in "Discussions" :)
