### ISSUE TITLE
rust has two kinds of integer literal

### ISSUE THREAD

**Issue by tromey** [Rust-GCC/gccrs#511]
I tried this code:

```rust
fn first(x : (i32, i32)) -> i32 {
    0_0 + x.0_0
}

pub fn main() {
    let y = first((2, 3));
}
```

This should give an error.  It's not very well documented (maybe not at all) but Rust has two kinds of integer literal: the ordinary kind that can use `_` as a separator, and also the "tuple" kind, where a separator cannot be used.

rustc gives an error on this code:
```
error[E0609]: no field `0_0` on type `(i32, i32)`
 --> tuple.rs:2:13
  |
2 |     0_0 + x.0_0
  |             ^^^
```

**Comment by philberty** [comment]
Good find I was not aware of this. I think this is a bug in the parser where we have the TupleIndexExpr:

https://github.com/Rust-GCC/gccrs/blob/f2d9faf3862a75247adbd6c233c889010902a34b/gcc/rust/ast/rust-expr.h#L1386

The TupleIndex is simply a typedef to int so I reckon the parser is reusing the normal flow for parsing an ineger which supports the 0_0 style but should not support it in this case. I think the bug is here:

https://github.com/Rust-GCC/gccrs/blob/f2d9faf3862a75247adbd6c233c889010902a34b/gcc/rust/parse/rust-parse-impl.h#L14076

Its actually doing an atoi on the string value.

**Comment by SimplyTheOther** [comment]
I believe that this is caused by the lexer ignoring the underscores when tokenising integer literals. A way to solve this could be to retain the underscores in the stored string representation of the integer literal, but this may lead to issues with non-decimal integer literals (i.e. they would have to be retained as well instead of converted to decimal in the lexer).
