### ISSUE TITLE
Update the CI to use -Werror

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#694]
We are using github automations for our PR's. Now that we have working bootstrap build lets avoid regressions here by adding -Werror to our CI

This is how we configure our build for CI automation in PR's

https://github.com/Rust-GCC/gccrs/blob/28f527c9598339cf834a30b5ee1f14258b8ecbb2/.github/workflows/ccpp.yml#L37-L44

Let's update this to add --enable-werror to catch warnings breaking the build again.

**Comment by tschwinge** [comment]
Note that GCC generally is only expected to be "warning-clean" without `--disable-bootstrap` (that is, default `--enable-bootstrap` for a native build; see #336), and not for the initial stage where it's using the "initial" compiler -- otherwise we're at the mercy of whatever "initial" compiler we're using.

**Comment by CastilloDel** [comment]
@tschwinge In the script it says that `--enable-werror` only enables `-Werror` in bootstrap stage2 and later ([check here](https://github.com/Rust-GCC/gccrs/blob/41f402f0b19c7e4f19f8d4d65d15223d2752f302/configure#L1579)). So it would be okay to add that and enable the bootstrap, right?

**Comment by CastilloDel** [comment]
I made a PR, please let me know if a change is needed! 😄
