### ISSUE TITLE
Allow redefining builltin macros

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#971]
rustc allows the redefinition of builtin macros. I am unsure whether or not this is an intended behavior, but we should probably look into it! Please feel free to chime in with additional info

```rust
macro_rules! file {
    () => { 14 }
}

fn main() {
    let a = file!(); // = 14, if we remove the declaration above it expands correctly to the file name
}
```

**Comment by bjorn3** [comment]
Builtin macros are defined in libcore as regular macros except with an attribute (`#[rustc_builtin_macro]`?) to replace their body with a compiler builtin implementation. This means they have the same shadowing and re-exporting behavior as macros actually defined inside libcore. The reason they look like they are always available is because they are part of libcore's prelude and thus get imported implicitly.
